version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16 # Opsional
    commands:
        - sudo yum install -y jq # Opsional
        - sudo yum install -y zip # Opsional
  build:
    commands:
      - echo "Building application..."
  post_build:
    commands:
      - echo "Build Complete"
      - echo "Deploying to EC2"
      - aws s3 cp ./index.html s3://tubes-devsecops-kalkulator-app/
      - aws s3 cp ./background.jpg s3://tubes-devsecops-kalkulator-app/
      - aws s3 cp ./readme.md s3://tubes-devsecops-kalkulator-app/
      - aws ec2 describe-instances --filters "Name=tag:Name,Values=TUBESdevsecops" | jq -r '.Reservations[].Instances[].PublicIpAddress' > ec2_public_ip.txt
      - PUBLIC_IP=$(cat ec2_public_ip.txt)
      - ssh -i ./TUBES (2).pem  ec2-user@$PUBLIC_IP "sudo rm -rf /var/www/html/*"
      - scp -i ./TUBES (2).pem ./index.html ec2-user@$PUBLIC_IP:/var/www/html/index.html
      - scp -i ./TUBES (2).pem ./background.jpg ec2-user@$PUBLIC_IP:/var/www/html/background.jpg
      - scp -i ./TUBES (2).pem ./readme.md ec2-user@$PUBLIC_IP:/var/www/html/readme.md
      - echo "Deployment complete"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
